name: ci-golang
on: 
  pull_request:
    branches:
      - develop

jobs:
  checks-application:
    strategy:
      matrix:
        go: ['1.21', '1.20', '1.22']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go
